spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v*/users/**, /springdoc/openapi3-user-service.json
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/v*/items/**, /springdoc/openapi3-item-service.json
#          filters:
#            - CustomFilter
      discovery:
        locator:
          enabled: true

server:
  port: 19080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /docs
#    url: /springdoc/openapi3-user-service.json
#    operations-sorter: alpha
#    tags-sorter: alpha
#  api-docs:
#    enabled: true
#    path: /docs/json

springdoc:
  swagger-ui:
    urls[0]:
      name: user-service
      url: /springdoc/openapi3-user-service.json
    urls[1]:
      name: item-service
      url: /springdoc/openapi3-item-service.json
#    use-root-path: true
    path: /docs